export GOPATH="$HOME/code/go"
export GO111MODULE=on

export PIPENV_VENV_IN_PROJECT="enabled"

export PATH="$HOME/.bin:$PATH"
export PATH="$(go env GOPATH)/bin:$PATH"
export PATH="/usr/local/opt/python@3.9/libexec/bin:$PATH"
export PATH="$PATH:/Users/erik/Library/Python/3.8/bin"
export PATH="$PATH:/usr/local/sbin"
