export GOPATH="$HOME/code/go"
export GO111MODULE=on

export PIPENV_VENV_IN_PROJECT="enabled"

# export PATH="$HOME/.cargo/bin:$PATH"
export PATH="/usr/local/sbin:$PATH"
export PATH="/usr/local/opt/python/libexec/bin:$PATH"
export PATH="$HOME/.bin:$PATH"
export PATH="$(go env GOPATH)/bin:$PATH"
export PATH="/Users/erik/Library/Python/3.7/bin:$PATH"
