export GOPATH="$HOME/code/go"
export GO111MODULE=on

export PIPENV_VENV_IN_PROJECT="enabled"

export PATH="/usr/local/sbin:$PATH"
export PATH="$HOME/.bin:$PATH"
export PATH="$(go env GOPATH)/bin:$PATH"